apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: demo-java
  name: demo-java
spec:
  replicas: 5
  selector:
    matchLabels:
      run: demo-java
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: demo-java
    spec:
      containers:
      - image: smile0x90/demo-java:v2
        env:
        - name: DB_URL
          value: "jdbc:mysql://localhost:3306/sakila?profileSQL=true"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        imagePullPolicy: Always #IfNotPresent
        name: demo-java
        ports:
        - containerPort: 8080
          protocol: TCP
      terminationGracePeriodSeconds: 30
