apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hello-java
  name: hello-java

spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-java
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: hello-java
    spec:
      containers:
      - image: smile0x90/hello-java:v1
        imagePullPolicy: Always
        name: hello-java
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
