apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-java
  name: demo-java
spec:
  ports:
  - port: 8080
    nodePort: 32014
    protocol: TCP
    targetPort: 8080
  selector:
    run: demo-java
  type: NodePort
